In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]
my_list2 = [5,3,5,2]
array1 = np.array(my_list1)

In [3]:
my_list1

[1, 2, 3, 4]

In [4]:
array1

array([1, 2, 3, 4])

In [6]:
my_lists = [my_list1,my_list2]
my_lists

[[1, 2, 3, 4], [5, 3, 5, 2]]

In [7]:
array = np.array(my_lists)
array

array([[1, 2, 3, 4],
       [5, 3, 5, 2]])

In [9]:
array.shape

(2, 4)

In [21]:
zeros = np.zeros([5,5])
zeros

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
ones = np.ones([2,4])
ones

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [25]:
identity = np.eye(4)
identity

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])